name: 'Gatling Enterprise Action'
description: 'Run your load tests on Gatling Enterprise straight from your GitHub Actions CI/CD workflows.'
branding:
  icon: 'bar-chart-2'
  color: 'purple'
inputs:
  gatling_enterprise_url:
    description: 'URL of your Gatling Enterprise server (needed only for self-hosted instances).'
    required: false
    default: 'https://cloud.gatling.io'
  api_token:
    description: 'A Gatling Enterprise API token with at least Start permission (we recommend storing it securely using GitHub''s encrypted secrets; see https://docs.github.com/en/actions/security-guides/encrypted-secrets#using-encrypted-secrets-in-a-workflow). Alternatively, you can define your token in an environment variable named GATLING_ENTERPRISE_API_TOKEN.'
    required: false
  simulation_id:
    description: 'The ID of the simulation to run.'
    required: true
  extra_system_properties:
    description: 'Additional Java system properties, will be merged with the simulation''s configured system properties. Must be formatted as a JSON object, e.g. {"MySysProp":"Some value"}.'
    required: false
  extra_environment_variables:
    description: 'Additional environment variables, will be merged with the simulation''s configured environment variables. Must be formatted as a JSON object, e.g. {"MY_ENV_VAR":"Some value"}.'
    required: false
  override_load_generators:
    description: 'Overrides the simulation''s load generators configuration. Must be formatted as a JSON object, e.g. {"4a399023-d443-3a58-864f-3919760df78b":{"size":1,"weight":60},"c800b6d9-163b-3db7-928f-86c1470a9542":{"size":1,"weight":40}} (weights are optional).'
    required: false
  fail_action_on_run_failure:
    description: 'Whether the action should fail if the run ends with a failed status. True by default. If set to false, some of this action''s outputs may be missing.'
    required: false
    default: 'true'
  wait_for_run_end:
    description: 'Whether the action should wait for the end of the Gatling Enterprise simulation run before terminating. True by default. If set to false, some of this action''s outputs may be missing.'
    required: false
    default: 'true'
  run_summary_enable:
    description: 'When wait_for_run_end is true, will regularly display a summary of the ongoing run in the console. True by default.'
    required: false
    default: 'true'
  run_summary_refresh_delay_constant:
    description: 'Constant part of the delay before displaying a new summary of the ongoing run in the console, in seconds. 5.0 seconds by default (which is the minimum). This initial delay grows exponentially by the factor set in run_summary_refresh_delay_multiplier to make the output less verbose. Note that the underlying data is only refreshed every 5 seconds, so the actual delay is approximate.'
    required: false
    default: '5.0'
  run_summary_refresh_delay_multiplier:
    description: 'A multiplier for the delay before displaying a new summary of the ongoing run in the console. 2.0 by default (minimum 1.0, which sets a constant delay). Every time a summary is displayed, the delay before the next one is multiplied by this value.'
    required: false
    default: '2.0'
  run_summary_refresh_delay_max:
    description: 'A maximum delay before displaying a new summary of the ongoing run in the console, in seconds. 300 seconds by default (minimum 5). The exponential increase of the delay will be capped to this value.'
    required: false
    default: '300'
outputs:
  run_id:
    description: 'ID of the run started by this action.'
  reports_url:
    description: 'The URL of the reports page for this run (only when running on Gatling Enterprise Cloud).'
  runs_url:
    description: 'The URL of the runs page for this simulation (only when running on Gatling Enterprise Cloud).'
  runs_status_code:
    description: 'The code of the run''s final status.'
  runs_status_name:
    description: 'The name of the run''s final status.'
  run_assertions:
    description: 'The results of the run''s assertions, as a JSON array.'
runs:
  using: 'node16'
  main: 'gh-action/dist/index.js'
  post: 'gh-action/dist/index.js'
