name: Publish

on:
  release:
    types:
      - published
      - edited

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      # Release with semantic tag like v1.0.3
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.release.tag_name }}
          
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Build
        run: |
          corepack enable
          yarn config set nodeLinker node-modules
          yarn plugin import workspace-tools
          yarn install --immutable
          yarn format-check
          yarn test
          yarn package

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Build and publish Docker runner (for GitLab CI/CD, etc.)
      - name: Publish Docker image
        working-directory: ./docker
        run: |
          full_version="${{ github.event.release.tag_name }}"
          full_version=${full_version//v/} # Remove 'v' prefix
          echo "full_version: $full_version"
          
          main_version=$(awk -F- '{print $1}' <<< "$full_version")
          major=$(awk -F '.' '{print $1}' <<< "$main_version")
          minor=$(awk -F '.' '{print $2}' <<< "$main_version")
          patch=$(awk -F '.' '{print $3}' <<< "$main_version")
          echo "major version: ${major}"
          echo "minor version: ${minor}"
          echo "patch version: ${patch}"
          
          prerelease=$(awk -F- '{print $2}' <<< "$full_version")
          echo "prerelease version: ${prerelease}"
          
          if [ -z "$prerelease" ]; then
            echo "Building Docker image with tags $major, $major.$minor, $major.$minor.$patch"
            docker build \
              --tag "gatlingcorp/enterprise-runner:$major" \
              --tag "gatlingcorp/enterprise-runner:$major.$minor" \
              --tag "gatlingcorp/enterprise-runner:$major.$minor.$patch" \
              .
            docker push "gatlingcorp/enterprise-runner:$major"
            docker push "gatlingcorp/enterprise-runner:$major.$minor"
            docker push "gatlingcorp/enterprise-runner:$major.$minor.$patch"
          else
            echo "Building Docker image with tag $full_version"
            docker build \
              --tag "gatlingcorp/enterprise-runner:$full_version" \
              .
            docker push "gatlingcorp/enterprise-runner:$full_version"
          fi

      # Create a commit with dist/index.js and action.yml
      # Force push major and minor tags, e.g. v1, v1.0
      # See documentation: https://github.com/JasonEtco/build-and-tag-action
      - name: Publish GitHub Action
        uses: JasonEtco/build-and-tag-action@v2
        env:
          GITHUB_TOKEN: ${{ github.token }}
