name: Run Gatling Enterprise Action

on:
  workflow_dispatch:
    inputs:
      simulation_id:
        type: string
        required: true
      extra_system_properties:
        type: string
        required: false
      extra_environment_variables:
        type: string
        required: false
      override_load_generators:
        type: string
        required: false

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build
        run: |
          yarn ci
          yarn package

      - name: Gatling Enterprise Action
        id: enterprise-action
        uses: ./
        with:
          api_token: ${{ secrets.TEST_CLOUD_PROD_GATLING_CORP_START_API_TOKEN }}
          simulation_id: ${{ inputs.simulation_id }}
          extra_system_properties: ${{ inputs.extra_system_properties }}
          extra_environment_variables: ${{ inputs.extra_environment_variables }}
          override_load_generators: ${{ inputs.override_load_generators }}

      - name: Print output
        run: |
          echo "run_id=${{ steps.enterprise-action.outputs.run_id }}"
          echo "reports_url=${{ steps.enterprise-action.outputs.reports_url }}"
          echo "runs_url=${{ steps.enterprise-action.outputs.runs_url }}"
          echo "runs_status_code=${{ steps.enterprise-action.outputs.runs_status_code }}"
          echo "runs_status_name=${{ steps.enterprise-action.outputs.runs_status_name }}"
          echo "run_assertions=${{ steps.enterprise-action.outputs.run_assertions }}"
